// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2g9c6MjGo0XgvI3aTkTo4rXMQxpb4zz0',
    appId: '1:745540130303:web:0034321ef2ab104f4d83ca',
    messagingSenderId: '745540130303',
    projectId: 'grammar-genie-ai',
    authDomain: 'grammar-genie-ai.firebaseapp.com',
    storageBucket: 'grammar-genie-ai.firebasestorage.app',
    measurementId: 'G-4XD50Y6ZEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMU0VI8Xas9eIOCFcaE43M3fd2SLWhKe0',
    appId: '1:745540130303:android:e921326c4908a28d4d83ca',
    messagingSenderId: '745540130303',
    projectId: 'grammar-genie-ai',
    storageBucket: 'grammar-genie-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBreHOiz3VmliTXpxKirpTzpCD96vVMm1o',
    appId: '1:745540130303:ios:082cded0ad4023244d83ca',
    messagingSenderId: '745540130303',
    projectId: 'grammar-genie-ai',
    storageBucket: 'grammar-genie-ai.firebasestorage.app',
    iosBundleId: 'com.example.grammarGenieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBreHOiz3VmliTXpxKirpTzpCD96vVMm1o',
    appId: '1:745540130303:ios:082cded0ad4023244d83ca',
    messagingSenderId: '745540130303',
    projectId: 'grammar-genie-ai',
    storageBucket: 'grammar-genie-ai.firebasestorage.app',
    iosBundleId: 'com.example.grammarGenieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2g9c6MjGo0XgvI3aTkTo4rXMQxpb4zz0',
    appId: '1:745540130303:web:10d01be92522ad3f4d83ca',
    messagingSenderId: '745540130303',
    projectId: 'grammar-genie-ai',
    authDomain: 'grammar-genie-ai.firebaseapp.com',
    storageBucket: 'grammar-genie-ai.firebasestorage.app',
    measurementId: 'G-TJNFHWTYXV',
  );
}
